// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	HelloWorld(ctx context.Context, opts ...grpc.CallOption) (TestService_HelloWorldClient, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) HelloWorld(ctx context.Context, opts ...grpc.CallOption) (TestService_HelloWorldClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], "/main.TestService/HelloWorld", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceHelloWorldClient{stream}
	return x, nil
}

type TestService_HelloWorldClient interface {
	Send(*HelloWorldRequest) error
	CloseAndRecv() (*HelloWorldResponse, error)
	grpc.ClientStream
}

type testServiceHelloWorldClient struct {
	grpc.ClientStream
}

func (x *testServiceHelloWorldClient) Send(m *HelloWorldRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceHelloWorldClient) CloseAndRecv() (*HelloWorldResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloWorldResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	HelloWorld(TestService_HelloWorldServer) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) HelloWorld(TestService_HelloWorldServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_HelloWorld_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).HelloWorld(&testServiceHelloWorldServer{stream})
}

type TestService_HelloWorldServer interface {
	SendAndClose(*HelloWorldResponse) error
	Recv() (*HelloWorldRequest, error)
	grpc.ServerStream
}

type testServiceHelloWorldServer struct {
	grpc.ServerStream
}

func (x *testServiceHelloWorldServer) SendAndClose(m *HelloWorldResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceHelloWorldServer) Recv() (*HelloWorldRequest, error) {
	m := new(HelloWorldRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloWorld",
			Handler:       _TestService_HelloWorld_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "test.proto",
}
